# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Python Script

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '05 16 * * *' # UTC 时间 16:05 北京时间大约 00:05
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install requirements dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
            
    - name: Update zhihu
      run: |
        python zhihu.py
        
    - name: Commit
      run: |
        git diff
        git config --global user.email lmm333@126.com
        git config --global user.name lmmsoft
        git add .
        #git commit -m"action:`date +'%Y-%m-%d'`"
        git commit -m "action: `date +'%Y-%m-%d %H:%M %z %Z'`"
        git pull --rebase

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
